stages:
  - build
  - test

build:
  stage: build
  tags:
    - blockbook
  script: make build

unit-test:
  stage: test
  tags:
    - blockbook
  script: make test

integration-test:
  stage: test
  tags:
    - blockbook
  script: make test-integration ARGS="-run='TestIntegration/(bcash|bgold|bitcoin|dash|dogecoin|litecoin|vertcoin|zcash)=main/'"
